name: "Subtitle Extract"
guid: "CD893C24-B59E-4060-87B2-184070E1BF68"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-subtitleextract.png"
version: 3
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Extracts Subtitles."
description: >
  Extracts embedded subtitles.

category: "General"
artifacts:
  - "Jellyfin.Plugin.SubtitleExtract.dll"
changelog: |-
  - 10.9 (#24) @crobibero

  ### New features and improvements ###
  - Allow for subtitles to be extracted for new media (#14) @Kakoluz

  ### Code or Repo Maintenance ###
  - Update link to Jellyfin website (#16) @methbkts
