name: "Subtitle Extract"
guid: "CD893C24-B59E-4060-87B2-184070E1BF68"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-subtitleextract.png"
version: 2
targetAbi: "10.8.4.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Extracts Subtitles."
description: >
  Extracts embedded subtitles.

category: "General"
artifacts:
  - "Jellyfin.Plugin.SubtitleExtract.dll"
changelog: |2-
  ### Bug Fixes ###
  - Catch exception when extracting (#1) @crobibero
